import {
  deleteCustomersByIds,
  getDemoCustomerIds,
  insertCustomer,
} from '../repositories/customer.repository';
import {
  deleteTermsByCustomerIds,
  insertTerm,
} from '../repositories/term.repository';
import { TERM_STATUS } from '../constants/termStatus';
import type { Term } from '../constants/term.types';
import type { TermStatus } from '../constants/termStatus';

const DEMO_CUSTOMERS = [
  {
    customerName: 'Ahmet Yılmaz',
    companyName: 'Yılmaz İnşaat A.Ş.',
    phone: '0532 111 1001',
    email: 'ahmet@demo.saha',
  },
  {
    customerName: 'Mehmet Demir',
    companyName: 'Demir Tekstil Ltd. Şti.',
    phone: '0533 111 1002',
    email: 'mehmet@demo.saha',
  },
  {
    customerName: 'Fatma Kaya',
    companyName: 'Kaya Gıda San. ve Tic. A.Ş.',
    phone: '0535 111 1003',
    email: 'fatma@demo.saha',
  },
  {
    customerName: 'Ali Şahin',
    companyName: 'Şahin Otomotiv',
    phone: '0542 111 1004',
    email: 'ali@demo.saha',
  },
  {
    customerName: 'Ayşe Çelik',
    companyName: 'Çelik Mobilya',
    phone: '0543 111 1005',
    email: 'ayse@demo.saha',
  },
  {
    customerName: 'Mustafa Yıldız',
    companyName: 'Yıldız Elektronik',
    phone: '0544 111 1006',
    email: 'mustafa@demo.saha',
  },
  {
    customerName: 'Zeynep Aydın',
    companyName: 'Aydın Tarım Makineleri',
    phone: '0545 111 1007',
    email: 'zeynep@demo.saha',
  },
  {
    customerName: 'Hasan Koç',
    companyName: 'Koç Nakliyat ve Lojistik',
    phone: '0546 111 1008',
    email: 'hasan@demo.saha',
  },
  {
    customerName: 'Emine Arslan',
    companyName: 'Arslan Kimya San.',
    phone: '0547 111 1009',
    email: 'emine@demo.saha',
  },
  {
    customerName: 'İbrahim Öztürk',
    companyName: 'Öztürk Medikal Cihazlar',
    phone: '0548 111 1010',
    email: 'ibrahim@demo.saha',
  },
  {
    customerName: 'Meral Doğan',
    companyName: 'Doğan Turizm ve Otelcilik',
    phone: '0549 111 1011',
    email: 'meral@demo.saha',
  },
  {
    customerName: 'Serkan Erdoğan',
    companyName: 'Erdoğan Makine İmalat',
    phone: '0550 111 1012',
    email: 'serkan@demo.saha',
  },
  {
    customerName: 'Büşra Aksoy',
    companyName: 'Aksoy Yazılım Çözümleri',
    phone: '0551 111 1013',
    email: 'busra@demo.saha',
  },
  {
    customerName: 'Cem Güneş',
    companyName: 'Güneş Enerji Sistemleri',
    phone: '0552 111 1014',
    email: 'cem@demo.saha',
  },
  {
    customerName: 'Pınar Polat',
    companyName: 'Polat Ambalaj ve Plastik',
    phone: '0553 111 1015',
    email: 'pinar@demo.saha',
  },
];

type DemoTerm = {
  ci: number; // customer index
  productName: string;
  orderDate: string;
  termDuration: string;
  expectedDate: string;
  status: TermStatus;
  arrivedAt: string | null;
  price: number;
  currency: string;
  stage: Term['stage'];
};

// 100 terms across 15 customers — varied statuses, stages, dates, prices and currencies
const DEMO_TERMS: DemoTerm[] = [
  // --- Yılmaz İnşaat (7) ---
  {
    ci: 0,
    productName: 'Endüstriyel Pompa Seti',
    orderDate: '2025-11-15',
    termDuration: '3 Ay',
    expectedDate: '2026-02-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-02-18',
    price: 45000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 0,
    productName: 'Jeneratör (250 kVA)',
    orderDate: '2025-09-01',
    termDuration: '6 Ay',
    expectedDate: '2026-03-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-03-05',
    price: 185000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 0,
    productName: 'Beton Mikseri',
    orderDate: '2026-03-10',
    termDuration: '2 Ay',
    expectedDate: '2026-05-10',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-05-12',
    price: 78000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 0,
    productName: 'Vinç (10 Ton)',
    orderDate: '2026-02-15',
    termDuration: '3 Ay',
    expectedDate: '2026-05-15',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 320000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 0,
    productName: 'Elektrik Panosu',
    orderDate: '2026-04-01',
    termDuration: '2 Ay',
    expectedDate: '2026-06-01',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 28000,
    currency: 'TRY',
    stage: 'firsat',
  },
  {
    ci: 0,
    productName: 'Kompresör (7.5 kW)',
    orderDate: '2026-05-01',
    termDuration: '1 Ay',
    expectedDate: '2026-06-01',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 22000,
    currency: 'TRY',
    stage: 'firsat',
  },
  {
    ci: 0,
    productName: 'Kazıyıcı Kepçe Takımı',
    orderDate: '2026-04-20',
    termDuration: '2 Ay',
    expectedDate: '2026-06-20',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 65000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },

  // --- Demir Tekstil (6) ---
  {
    ci: 1,
    productName: 'Halı Dokuma Makinesi',
    orderDate: '2025-06-01',
    termDuration: '6 Ay',
    expectedDate: '2025-12-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-12-05',
    price: 290000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 1,
    productName: 'Boya Tekne Sistemi',
    orderDate: '2025-10-15',
    termDuration: '3 Ay',
    expectedDate: '2026-01-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-01-18',
    price: 125000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 1,
    productName: 'İplik Sarma Makinesi',
    orderDate: '2026-01-10',
    termDuration: '2 Ay',
    expectedDate: '2026-03-10',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-03-15',
    price: 67000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 1,
    productName: 'Tekstil Baskı Makinesi',
    orderDate: '2026-03-01',
    termDuration: '3 Ay',
    expectedDate: '2026-06-01',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 240000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 1,
    productName: 'Kumaş Yıkama Ünitesi',
    orderDate: '2026-04-15',
    termDuration: '2 Ay',
    expectedDate: '2026-06-15',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 89000,
    currency: 'TRY',
    stage: 'firsat',
  },
  {
    ci: 1,
    productName: 'Konveyör Bant (20m)',
    orderDate: '2026-05-05',
    termDuration: '1 Ay',
    expectedDate: '2026-06-05',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 31000,
    currency: 'TRY',
    stage: 'firsat',
  },

  // --- Kaya Gıda (7) ---
  {
    ci: 2,
    productName: 'Su Arıtma Sistemi',
    orderDate: '2025-07-01',
    termDuration: '3 Ay',
    expectedDate: '2025-10-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-10-05',
    price: 55000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 2,
    productName: 'Soğuk Hava Deposu (50 m²)',
    orderDate: '2025-08-01',
    termDuration: '4 Ay',
    expectedDate: '2025-12-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-12-08',
    price: 180000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 2,
    productName: 'Gıda Paketleme Makinesi',
    orderDate: '2025-12-01',
    termDuration: '2 Ay',
    expectedDate: '2026-02-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-02-03',
    price: 95000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 2,
    productName: 'Endüstriyel Fırın (3 Katlı)',
    orderDate: '2026-01-15',
    termDuration: '2 Ay',
    expectedDate: '2026-03-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-03-20',
    price: 142000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 2,
    productName: 'Sterilizasyon Ünitesi',
    orderDate: '2026-03-10',
    termDuration: '2 Ay',
    expectedDate: '2026-05-10',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 76000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 2,
    productName: 'Soğutma Sistemi',
    orderDate: '2026-04-01',
    termDuration: '2 Ay',
    expectedDate: '2026-06-01',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 85000,
    currency: 'TRY',
    stage: 'firsat',
  },
  {
    ci: 2,
    productName: 'Konveyör Bant (Gıda Tipi)',
    orderDate: '2026-05-10',
    termDuration: '6 Hafta',
    expectedDate: '2026-06-21',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 28000,
    currency: 'TRY',
    stage: 'firsat',
  },

  // --- Şahin Otomotiv (7) ---
  {
    ci: 3,
    productName: 'Araç Lift (4 Ton)',
    orderDate: '2025-09-15',
    termDuration: '2 Ay',
    expectedDate: '2025-11-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-11-20',
    price: 48000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 3,
    productName: 'Teşhis Cihazı (OBD)',
    orderDate: '2026-01-01',
    termDuration: '1 Ay',
    expectedDate: '2026-02-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-02-05',
    price: 22000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 3,
    productName: 'Lastik Balans Makinesi',
    orderDate: '2026-02-01',
    termDuration: '2 Ay',
    expectedDate: '2026-04-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-04-06',
    price: 35000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 3,
    productName: 'Akü Şarj İstasyonu',
    orderDate: '2026-04-10',
    termDuration: '1 Ay',
    expectedDate: '2026-05-10',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-05-14',
    price: 18500,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 3,
    productName: 'Araç Yıkama Sistemi',
    orderDate: '2026-03-20',
    termDuration: '2 Ay',
    expectedDate: '2026-05-20',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 115000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 3,
    productName: 'Fren Test Cihazı',
    orderDate: '2026-04-25',
    termDuration: '2 Ay',
    expectedDate: '2026-06-25',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 42000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 3,
    productName: 'Motor Test Standı',
    orderDate: '2026-05-01',
    termDuration: '3 Ay',
    expectedDate: '2026-08-01',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 290000,
    currency: 'USD',
    stage: 'firsat',
  },

  // --- Çelik Mobilya (6) ---
  {
    ci: 4,
    productName: 'CNC Ahşap İşleme Makinesi',
    orderDate: '2025-07-01',
    termDuration: '5 Ay',
    expectedDate: '2025-12-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-12-04',
    price: 385000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 4,
    productName: 'Boyama Kabini',
    orderDate: '2025-11-15',
    termDuration: '2 Ay',
    expectedDate: '2026-01-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-01-18',
    price: 95000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 4,
    productName: 'Mobilya Paketleme Makinesi',
    orderDate: '2026-02-01',
    termDuration: '3 Ay',
    expectedDate: '2026-05-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-05-06',
    price: 78000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 4,
    productName: 'Ahşap Kurutma Fırını',
    orderDate: '2026-03-15',
    termDuration: '2 Ay',
    expectedDate: '2026-05-15',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 145000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 4,
    productName: 'Kesme Makinesi (Panel)',
    orderDate: '2026-04-20',
    termDuration: '1 Ay',
    expectedDate: '2026-05-20',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 62000,
    currency: 'TRY',
    stage: 'firsat',
  },
  {
    ci: 4,
    productName: 'Zımpara Ünitesi (Otomatik)',
    orderDate: '2026-05-10',
    termDuration: '2 Ay',
    expectedDate: '2026-07-10',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 41000,
    currency: 'TRY',
    stage: 'firsat',
  },

  // --- Yıldız Elektronik (7) ---
  {
    ci: 5,
    productName: 'Röntgen Test Cihazı (PCB)',
    orderDate: '2025-08-01',
    termDuration: '4 Ay',
    expectedDate: '2025-12-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-12-10',
    price: 640000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 5,
    productName: 'SMT Montaj Makinesi',
    orderDate: '2025-05-01',
    termDuration: '6 Ay',
    expectedDate: '2025-11-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-11-08',
    price: 520000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 5,
    productName: 'Dalga Lehimleme Makinesi',
    orderDate: '2025-10-01',
    termDuration: '3 Ay',
    expectedDate: '2026-01-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-01-05',
    price: 195000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 5,
    productName: 'AOI Test Sistemi',
    orderDate: '2026-01-15',
    termDuration: '3 Ay',
    expectedDate: '2026-04-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-04-20',
    price: 280000,
    currency: 'EUR',
    stage: 'kazanildi',
  },
  {
    ci: 5,
    productName: 'ESD Test Ekipmanı',
    orderDate: '2026-03-01',
    termDuration: '2 Ay',
    expectedDate: '2026-05-01',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 45000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 5,
    productName: 'Kalite Kontrol Kamerası (Set)',
    orderDate: '2026-05-05',
    termDuration: '2 Ay',
    expectedDate: '2026-07-05',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 125000,
    currency: 'TRY',
    stage: 'firsat',
  },
  {
    ci: 5,
    productName: 'PCB Lazer Kesici',
    orderDate: '2026-04-01',
    termDuration: '3 Ay',
    expectedDate: '2026-07-01',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 380000,
    currency: 'EUR',
    stage: 'kaybedildi',
  },

  // --- Aydın Tarım (7) ---
  {
    ci: 6,
    productName: 'Toprak Frezesi',
    orderDate: '2025-09-01',
    termDuration: '1 Ay',
    expectedDate: '2025-10-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-10-04',
    price: 35000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 6,
    productName: 'Hasat Makinesi Yedek Parça',
    orderDate: '2026-01-10',
    termDuration: '6 Hafta',
    expectedDate: '2026-02-21',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-02-25',
    price: 18000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 6,
    productName: 'Sulama Sistemi (Damla)',
    orderDate: '2025-12-01',
    termDuration: '2 Ay',
    expectedDate: '2026-02-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-02-08',
    price: 68000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 6,
    productName: 'Gübre Dağıtma Makinesi',
    orderDate: '2026-02-15',
    termDuration: '1 Ay',
    expectedDate: '2026-03-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-03-18',
    price: 28000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 6,
    productName: 'Tarım Dronu (6 Kollu)',
    orderDate: '2026-03-01',
    termDuration: '3 Ay',
    expectedDate: '2026-06-01',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 95000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 6,
    productName: 'Soğuk Hava Odası (Tarım)',
    orderDate: '2026-04-01',
    termDuration: '2 Ay',
    expectedDate: '2026-06-01',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 145000,
    currency: 'TRY',
    stage: 'firsat',
  },
  {
    ci: 6,
    productName: 'Tohum Ekim Makinesi',
    orderDate: '2026-05-01',
    termDuration: '1 Ay',
    expectedDate: '2026-06-01',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 42000,
    currency: 'TRY',
    stage: 'firsat',
  },

  // --- Koç Nakliyat (6) ---
  {
    ci: 7,
    productName: 'TIR Soğutma Ünitesi (2 Adet)',
    orderDate: '2025-10-01',
    termDuration: '2 Ay',
    expectedDate: '2025-12-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-12-05',
    price: 185000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 7,
    productName: 'Forklift (3 Ton)',
    orderDate: '2026-01-01',
    termDuration: '3 Ay',
    expectedDate: '2026-04-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-04-08',
    price: 245000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 7,
    productName: 'Depo Raf Sistemi',
    orderDate: '2026-02-01',
    termDuration: '2 Ay',
    expectedDate: '2026-04-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-04-05',
    price: 78000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 7,
    productName: 'GPS Takip Sistemi (Fleet)',
    orderDate: '2026-03-15',
    termDuration: '1 Ay',
    expectedDate: '2026-04-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-04-17',
    price: 45000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 7,
    productName: 'Rampa Köprüsü (Hidrolik)',
    orderDate: '2026-04-01',
    termDuration: '2 Ay',
    expectedDate: '2026-06-01',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 62000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 7,
    productName: 'Palet Makinesi (Elektrikli)',
    orderDate: '2026-05-01',
    termDuration: '1 Ay',
    expectedDate: '2026-06-01',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 38000,
    currency: 'TRY',
    stage: 'firsat',
  },

  // --- Arslan Kimya (7) ---
  {
    ci: 8,
    productName: 'Laboratuvar Ekipmanı (Set)',
    orderDate: '2025-09-01',
    termDuration: '2 Ay',
    expectedDate: '2025-11-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-11-06',
    price: 125000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 8,
    productName: 'Reaktör (Paslanmaz 5000L)',
    orderDate: '2025-06-01',
    termDuration: '6 Ay',
    expectedDate: '2025-12-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-12-10',
    price: 850000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 8,
    productName: 'Kimyasal Dozaj Pompaları',
    orderDate: '2026-01-01',
    termDuration: '2 Ay',
    expectedDate: '2026-03-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-03-08',
    price: 95000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 8,
    productName: 'Atık Su Arıtma Ünitesi',
    orderDate: '2026-02-15',
    termDuration: '3 Ay',
    expectedDate: '2026-05-15',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 320000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 8,
    productName: 'Havalandırma Sistemi',
    orderDate: '2026-03-20',
    termDuration: '2 Ay',
    expectedDate: '2026-05-20',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 145000,
    currency: 'TRY',
    stage: 'firsat',
  },
  {
    ci: 8,
    productName: 'Depolama Tankı (5000L PP)',
    orderDate: '2026-04-10',
    termDuration: '6 Hafta',
    expectedDate: '2026-05-22',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 48000,
    currency: 'TRY',
    stage: 'firsat',
  },
  {
    ci: 8,
    productName: 'HVAC Sistemi (Endüstriyel)',
    orderDate: '2026-05-08',
    termDuration: '3 Ay',
    expectedDate: '2026-08-08',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 285000,
    currency: 'TRY',
    stage: 'kaybedildi',
  },

  // --- Öztürk Medikal (7) ---
  {
    ci: 9,
    productName: 'Ultrason Cihazı (Portabl)',
    orderDate: '2025-08-15',
    termDuration: '3 Ay',
    expectedDate: '2025-11-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-11-20',
    price: 185000,
    currency: 'USD',
    stage: 'kazanildi',
  },
  {
    ci: 9,
    productName: 'Sterilizasyon Otoklavı',
    orderDate: '2025-11-01',
    termDuration: '2 Ay',
    expectedDate: '2026-01-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-01-08',
    price: 145000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 9,
    productName: 'Hasta Yatağı (20 Adet)',
    orderDate: '2026-01-15',
    termDuration: '6 Hafta',
    expectedDate: '2026-03-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-03-06',
    price: 78000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 9,
    productName: 'EKG Cihazı (12 Kanal)',
    orderDate: '2026-02-20',
    termDuration: '2 Ay',
    expectedDate: '2026-04-20',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-04-25',
    price: 42000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 9,
    productName: 'Tansiyon Cihazı (50 Adet)',
    orderDate: '2026-04-15',
    termDuration: '1 Ay',
    expectedDate: '2026-05-15',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 25000,
    currency: 'TRY',
    stage: 'firsat',
  },
  {
    ci: 9,
    productName: 'Anestezi Cihazı',
    orderDate: '2026-03-01',
    termDuration: '3 Ay',
    expectedDate: '2026-06-01',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 380000,
    currency: 'EUR',
    stage: 'teklif_verildi',
  },
  {
    ci: 9,
    productName: 'Kan Tahlil Cihazı',
    orderDate: '2026-05-10',
    termDuration: '3 Ay',
    expectedDate: '2026-08-10',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 220000,
    currency: 'USD',
    stage: 'firsat',
  },

  // --- Doğan Turizm (6) ---
  {
    ci: 10,
    productName: 'Restoran Mutfak Ekipmanı',
    orderDate: '2025-09-01',
    termDuration: '3 Ay',
    expectedDate: '2025-12-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-12-12',
    price: 285000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 10,
    productName: 'Klima Sistemi (VRF)',
    orderDate: '2025-11-15',
    termDuration: '2 Ay',
    expectedDate: '2026-01-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-01-22',
    price: 195000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 10,
    productName: 'Yüzme Havuzu Ekipmanı',
    orderDate: '2026-01-01',
    termDuration: '3 Ay',
    expectedDate: '2026-04-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-04-10',
    price: 145000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 10,
    productName: 'Güvenlik Kamera Sistemi',
    orderDate: '2026-02-15',
    termDuration: '1 Ay',
    expectedDate: '2026-03-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-03-18',
    price: 48000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 10,
    productName: 'Otel Mobilyası (50 Oda)',
    orderDate: '2026-03-10',
    termDuration: '3 Ay',
    expectedDate: '2026-06-10',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 420000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 10,
    productName: 'Çamaşırhane Makineleri',
    orderDate: '2026-04-20',
    termDuration: '2 Ay',
    expectedDate: '2026-06-20',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 125000,
    currency: 'TRY',
    stage: 'firsat',
  },

  // --- Erdoğan Makine (7) ---
  {
    ci: 11,
    productName: 'Freze Makinesi Yedek Parça',
    orderDate: '2025-10-01',
    termDuration: '6 Hafta',
    expectedDate: '2025-11-12',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-11-15',
    price: 28000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 11,
    productName: 'CNC Torna Makinesi',
    orderDate: '2025-07-01',
    termDuration: '5 Ay',
    expectedDate: '2025-12-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-12-08',
    price: 425000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 11,
    productName: 'Plazma Kesim Tezgahı',
    orderDate: '2026-01-01',
    termDuration: '2 Ay',
    expectedDate: '2026-03-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-03-05',
    price: 285000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 11,
    productName: 'Taşlama Makinesi (Silindirik)',
    orderDate: '2026-03-15',
    termDuration: '2 Ay',
    expectedDate: '2026-05-15',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 185000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 11,
    productName: 'Delme Tezgahı (Radyal)',
    orderDate: '2026-04-10',
    termDuration: '1 Ay',
    expectedDate: '2026-05-10',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 65000,
    currency: 'TRY',
    stage: 'firsat',
  },
  {
    ci: 11,
    productName: 'Kaynak Robotu',
    orderDate: '2026-02-01',
    termDuration: '4 Ay',
    expectedDate: '2026-06-01',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 680000,
    currency: 'EUR',
    stage: 'teklif_verildi',
  },
  {
    ci: 11,
    productName: 'Pres Makinesi (100 Ton)',
    orderDate: '2026-05-05',
    termDuration: '3 Ay',
    expectedDate: '2026-08-05',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 480000,
    currency: 'TRY',
    stage: 'kaybedildi',
  },

  // --- Aksoy Yazılım (6) ---
  {
    ci: 12,
    productName: 'ERP Sistemi Lisansı (3 Yıl)',
    orderDate: '2025-10-01',
    termDuration: '1 Ay',
    expectedDate: '2025-11-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-11-03',
    price: 285000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 12,
    productName: 'Sunucu (Dell PowerEdge)',
    orderDate: '2025-12-01',
    termDuration: '6 Hafta',
    expectedDate: '2026-01-12',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-01-15',
    price: 185000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 12,
    productName: 'Siber Güvenlik Yazılımı',
    orderDate: '2026-02-01',
    termDuration: '1 Ay',
    expectedDate: '2026-03-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-03-04',
    price: 45000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 12,
    productName: 'Bulut Depolama (5TB/Yıl)',
    orderDate: '2026-03-15',
    termDuration: '2 Hafta',
    expectedDate: '2026-03-29',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-03-30',
    price: 28000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 12,
    productName: 'Mobil Uygulama Geliştirme',
    orderDate: '2026-04-01',
    termDuration: '3 Ay',
    expectedDate: '2026-07-01',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 380000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 12,
    productName: 'IT Altyapı Danışmanlığı',
    orderDate: '2026-05-01',
    termDuration: '2 Ay',
    expectedDate: '2026-07-01',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 95000,
    currency: 'TRY',
    stage: 'kaybedildi',
  },

  // --- Güneş Enerji (7) ---
  {
    ci: 13,
    productName: 'Enerji Yönetim Yazılımı',
    orderDate: '2025-08-01',
    termDuration: '2 Ay',
    expectedDate: '2025-10-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-10-05',
    price: 85000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 13,
    productName: 'Solar Panel Sistemi (100 kW)',
    orderDate: '2025-06-01',
    termDuration: '4 Ay',
    expectedDate: '2025-10-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-10-08',
    price: 850000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 13,
    productName: 'İnverter (3 Faz, 100 kW)',
    orderDate: '2025-10-15',
    termDuration: '2 Ay',
    expectedDate: '2025-12-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-12-20',
    price: 285000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 13,
    productName: 'Akü Depolama Sistemi',
    orderDate: '2026-01-15',
    termDuration: '3 Ay',
    expectedDate: '2026-04-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-04-22',
    price: 680000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 13,
    productName: 'Şarj İstasyonu (DC Hızlı)',
    orderDate: '2026-03-01',
    termDuration: '2 Ay',
    expectedDate: '2026-05-01',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 245000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 13,
    productName: 'Güneş Takip Sistemi',
    orderDate: '2026-04-15',
    termDuration: '3 Ay',
    expectedDate: '2026-07-15',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 380000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 13,
    productName: 'Kablo ve Bağlantı Ekipmanı',
    orderDate: '2026-05-10',
    termDuration: '1 Ay',
    expectedDate: '2026-06-10',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 48000,
    currency: 'TRY',
    stage: 'firsat',
  },

  // --- Polat Ambalaj (7) ---
  {
    ci: 14,
    productName: 'Baskı Makinesi (Dijital)',
    orderDate: '2025-09-20',
    termDuration: '6 Hafta',
    expectedDate: '2025-11-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-11-05',
    price: 385000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 14,
    productName: 'Shrink Ambalaj Makinesi',
    orderDate: '2025-08-15',
    termDuration: '3 Ay',
    expectedDate: '2025-11-15',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2025-11-20',
    price: 185000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 14,
    productName: 'Karton Kutu Yapıştırma Mak.',
    orderDate: '2025-11-01',
    termDuration: '2 Ay',
    expectedDate: '2026-01-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-01-08',
    price: 245000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 14,
    productName: 'Termoform Makinesi',
    orderDate: '2026-01-20',
    termDuration: '2 Ay',
    expectedDate: '2026-03-20',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-03-25',
    price: 325000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 14,
    productName: 'Bant Sarım Makinesi',
    orderDate: '2026-03-01',
    termDuration: '1 Ay',
    expectedDate: '2026-04-01',
    status: TERM_STATUS.ARRIVED,
    arrivedAt: '2026-04-05',
    price: 78000,
    currency: 'TRY',
    stage: 'kazanildi',
  },
  {
    ci: 14,
    productName: 'Etiketleme Makinesi (Oto.)',
    orderDate: '2026-04-05',
    termDuration: '2 Ay',
    expectedDate: '2026-06-05',
    status: TERM_STATUS.PENDING,
    arrivedAt: null,
    price: 145000,
    currency: 'TRY',
    stage: 'teklif_verildi',
  },
  {
    ci: 14,
    productName: 'Plastik Enjeksiyon Kalıpları',
    orderDate: '2026-05-08',
    termDuration: '3 Ay',
    expectedDate: '2026-08-08',
    status: TERM_STATUS.ORDERED,
    arrivedAt: null,
    price: 285000,
    currency: 'TRY',
    stage: 'firsat',
  },
];

export type SeedResult =
  | { alreadyExists: true }
  | { alreadyExists: false; customerCount: number; termCount: number };

export function seedDemoData(): SeedResult {
  const existingIds = getDemoCustomerIds();
  if (existingIds.length > 0) {
    return { alreadyExists: true };
  }

  // Not: seedDemoData needs to mark demo customers as isDemo=1.
  // Also ensure the new column exists for existing DBs.
  const customerIds: number[] = [];
  for (const customer of DEMO_CUSTOMERS) {
    const customerId = insertCustomer({
      ...customer,
      isDemo: 1,
    });

    customerIds.push(customerId);
  }

  for (const t of DEMO_TERMS) {
    insertTerm({
      customerId: customerIds[t.ci],
      productName: t.productName,
      orderDate: t.orderDate,
      termDuration: t.termDuration,
      expectedDate: t.expectedDate,
      status: t.status,
      arrivedAt: t.arrivedAt,
      price: t.price,
      currency: t.currency,
      stage: t.stage,
    });
  }

  return {
    alreadyExists: false,
    customerCount: customerIds.length,
    termCount: DEMO_TERMS.length,
  };
}

export function clearDemoData(): number {
  const ids = getDemoCustomerIds();
  if (ids.length === 0) return 0;

  deleteTermsByCustomerIds(ids);
  deleteCustomersByIds(ids);
  return ids.length;
}
